#ifndef QTDMESSAGECHATSETMESSAGEAUTODELETETIME_H
#define QTDMESSAGECHATSETMESSAGEAUTODELETETIME_H

/*
 * WARNING: This is a generated file. Do not modify directly.
 * Any changes made to this file will be overwritten.
 * 
 * Generated on: 2024-07-05
 * Generated by: TELEports tlparser.py
 * 
 * For any modifications, please edit the source templates and regenerate this file.
 */

#include <QObject>
#include <QList>
#include "common/qabstracttdobject.h"
#include "messages/qtdmessagecontent.h"

class QTdMessageChatSetMessageAutoDeleteTime : public QTdMessageContent {
    Q_OBJECT
    Q_PROPERTY(qint32 messageAutoDeleteTime READ messageAutoDeleteTime WRITE setMessageAutoDeleteTime NOTIFY dataChanged)
    Q_PROPERTY(qint64 fromUserId READ fromUserId WRITE setFromUserId NOTIFY dataChanged)

public:
    explicit QTdMessageChatSetMessageAutoDeleteTime(QObject *parent = nullptr);
    explicit QTdMessageChatSetMessageAutoDeleteTime(QObject *parent, qint32 messageAutoDeleteTime_, qint64 fromUserId_);

    qint32 messageAutoDeleteTime() const;
    void setMessageAutoDeleteTime(qint32 value);
    qint64 fromUserId() const;
    void setFromUserId(qint64 value);

    void unmarshalJson(const QJsonObject &json) override;
    QJsonObject marshalJson() override;

private:
    Q_DISABLE_COPY(QTdMessageChatSetMessageAutoDeleteTime)
    qint32 m_messageAutoDeleteTime;
    qint64 m_fromUserId;

signals:
    void dataChanged();

};

#endif // QTDMESSAGECHATSETMESSAGEAUTODELETETIME_H
