#ifndef QTDEMOJISTATUS_H
#define QTDEMOJISTATUS_H

/*
 * WARNING: This is a generated file. Do not modify directly.
 * Any changes made to this file will be overwritten.
 * 
 * Generated on: 2024-07-08
 * Generated by: TELEports tlparser.py
 * 
 * For any modifications, please edit the source templates and regenerate this file.
 */

#include <QObject>
#include <QList>
#include "common/qabstracttdobject.h"

/**
 * @brief The QTdEmojiStatus class
 *
 */
class QTdEmojiStatus : public QTdObject {
    Q_OBJECT
    Q_PROPERTY(qint64 customEmojiId READ customEmojiId WRITE setCustomEmojiId NOTIFY dataChanged)

public:
    explicit QTdEmojiStatus(QObject *parent = nullptr);
    explicit QTdEmojiStatus(QObject *parent, qint64 customEmojiId_);

    qint64 customEmojiId() const;
    void setCustomEmojiId(qint64 value);

    void unmarshalJson(const QJsonObject &json) override;
    QJsonObject marshalJson() override;

private:
    Q_DISABLE_COPY(QTdEmojiStatus)
    qint64 m_customEmojiId;

signals:
    void dataChanged();

};

#endif // QTDEMOJISTATUS_H
